baseURL = 'http://localhost:1313/' #TODO: Change to url on initial commit
languageCode = 'en-us'
title = 'BYTEQUILL'
copyright = '©2024-2024 bytequill, under MIT license'

[params]
subtitle = 'A COMPUTER NERD'